### ISSUE TITLE
eager load can't create user

### ISSUE THREAD

**Issue by kulik** [kont-noor/Theblog#20]
d not found: Incarnator::Account.create
➜  tacblog  bundle exec rails c Incarnator::Account.create email: 'fake@mail.com', user_name: 'username', password: 'password', confirmed_at Time.now
config.eager_load is set to nil. Please update your config/environments/*.rb files accordingly:

  * development - set it to false
  * test - set it to false (unless you use a tool that preloads your test environment)
  * production - set it to true

/var/lib/gems/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/connection_specification.rb:248:in `resolve_symbol_connection': 'Incarnator::Account.create' database is not configured. Available: ["default", "development", "test", "production"] (ActiveRecord::AdapterNotSpecified)
	from /var/lib/gems/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/connection_specification.rb:211:in `resolve_connection'
	from /var/lib/gems/2.1.0/gems/active

**Comment by kulik** [comment]
stuped by itself))
